"""Per-engagement scoping for Neo4j writes and reads.

The Neo4j container is dual-homed across `sandbox-net` and
`decepticon-net` (see `docs/security/neo4j-hardening.md`). Every write
from inside the sandbox needs to land tagged with the engagement it
belongs to so:

  * The web dashboard's `engagements/[id]/graph` route can filter the
    graph view to one engagement.
  * Multi-tenant SaaS deployments cannot leak engagement A's findings
    into engagement B's view through a shared Neo4j instance.
  * Out-brief deliverables can be generated by selecting all nodes
    matching one engagement label.

This module exposes a context-variable based active-engagement getter
that the Neo4j store consults on every upsert and the Cypher builder
consults on every read. Setting the value is the launcher's
responsibility - the `EngagementContextMiddleware` resolves
`engagement_name` from `config.configurable` on the first turn and
calls `set_active_engagement(...)` before tool dispatch.

Legacy data (nodes written before the scoping landed) carries no
`engagement` property. The migration helper
`migrate_engagement_property` retags those nodes with a default
engagement name supplied by the operator.
"""

from __future__ import annotations

import contextvars
import logging
import os
import re

log = logging.getLogger(__name__)


_active_engagement: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "decepticon_active_engagement",
    default=None,
)


_LEGACY_ENGAGEMENT_LABEL = "_legacy"
_ENGAGEMENT_LABEL_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._\-]{0,127}$")


def is_valid_engagement_label(label: str) -> bool:
    """Return True if ``label`` is a safe engagement identifier.

    Characters are restricted to ASCII alphanumeric plus ``.``, ``-``,
    ``_``. The first character must be alphanumeric. Length 1-128. This
    keeps the property safe to interpolate into Cypher (it's still
    parameter-bound in our queries, but defense in depth) and safe to
    use as a filesystem subpath.
    """
    return bool(label and _ENGAGEMENT_LABEL_RE.match(label))


def set_active_engagement(label: str | None) -> contextvars.Token:
    """Set the active engagement label for the current context.

    Pass ``None`` to clear (uncommon - usually you push a new value
    via this function and pop via the returned token).
    """
    if label is not None and not is_valid_engagement_label(label):
        raise ValueError(
            f"invalid engagement label {label!r}; must match [A-Za-z0-9][A-Za-z0-9._-]{{0,127}}"
        )
    return _active_engagement.set(label)


def reset_active_engagement(token: contextvars.Token) -> None:
    """Reset the active engagement to the value before ``set_active_engagement``."""
    _active_engagement.reset(token)


def get_active_engagement() -> str | None:
    """Return the active engagement label, or ``None`` if unset.

    Resolution order (first non-empty wins):
      1. contextvar set by ``set_active_engagement``
      2. ``DECEPTICON_ENGAGEMENT`` environment variable
      3. ``None`` (caller should treat as "no scoping configured")
    """
    label = _active_engagement.get()
    if label:
        return label
    env_label = os.environ.get("DECEPTICON_ENGAGEMENT", "").strip()
    if env_label and is_valid_engagement_label(env_label):
        return env_label
    return None


def with_engagement_property(props: dict | None, *, override: str | None = None) -> dict:
    """Return ``props`` with an ``engagement`` key set to the right label.

    Precedence (first non-empty wins): ``override`` (caller pins it) → an
    ``engagement`` already on ``props`` → the active engagement → the legacy
    label. Preserving an existing ``engagement`` is the multi-tenant safety
    invariant: it stops a ``graph_transaction`` save-back from relabelling a
    loaded node onto the current (or ``_legacy``) engagement on a shared
    Neo4j. See docs/security/neo4j-hardening.md.
    """
    out = dict(props or {})
    engagement = (
        override or out.get("engagement") or get_active_engagement() or _LEGACY_ENGAGEMENT_LABEL
    )
    out["engagement"] = engagement
    return out
